name: build_and_test

on: [push, pull_request]

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@main
        - uses: denoland/setup-deno@v2
        - name: prepare vulkan sdk
          uses: humbletim/setup-vulkan-sdk@main
          with:
            vulkan-query-version: 1.4.335.0
            vulkan-components: Vulkan-Headers, Vulkan-Loader
            vulkan-use-cache: true
        - name: sapp-vk-win-msvc-debug
          run:  |
            ./fibs config sapp-vk-win-msvc-debug
            ./fibs build
        - name: sapp-vk-win-msvc-release
          run: |
            ./fibs config sapp-vk-win-msvc-release
            ./fibs build
        - name: sapp-d3d11-win-msvc-debug
          run: |
            ./fibs config sapp-d3d11-win-msvc-debug
            ./fibs build
        - name: sapp-d3d11-win-msvc-release
          run: |
            ./fibs config sapp-d3d11-win-msvc-release
            ./fibs build
        - name: sapp-gl-win-msvc-debug
          run: |
            ./fibs config sapp-gl-win-msvc-debug
            ./fibs build
        - name: sapp-gl-win-msvc-release
          run: |
            ./fibs config sapp-gl-win-msvc-release
            ./fibs build
        - name: d3d11-win-msvc-debug
          run: |
            ./fibs config d3d11-win-msvc-debug
            ./fibs build
        - name: d3d11-win-msvc-release
          run: |
            ./fibs config d3d11-win-msvc-release
            ./fibs build
        - name: glfw-win-msvc-debug
          run: |
            ./fibs config glfw-win-msvc-debug
            ./fibs build
        - name: glfw-win-msvc-release
          run: |
            ./fibs config glfw-win-msvc-release
            ./fibs build
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@main
        - uses: ashutoshvarma/setup-ninja@master
        - uses: denoland/setup-deno@v2
        - name: sapp-metal-macos-ninja-debug
          run: |
            ./fibs config sapp-metal-macos-ninja-debug
            ./fibs build
        - name: sapp-metal-macos-ninja-release
          run: |
            ./fibs config sapp-metal-macos-ninja-release
            ./fibs build
        - name: sapp-gl-macos-ninja-debug
          run: |
            ./fibs config sapp-gl-macos-ninja-debug
            ./fibs build
        - name: sapp-gl-macos-ninja-release
          run: |
            ./fibs config sapp-gl-macos-ninja-release
            ./fibs build
        - name: metal-macos-ninja-debug
          run: |
            /fibs config metal-macos-ninja-debug
            ./fibs build
        - name: metal-macos-ninja-release
          run: |
            ./fibs config metal-macos-ninja-release
            ./fibs build
        - name: glfw-macos-ninja-debug
          run: |
            /fibs config glfw-macos-ninja-debug
            ./fibs build
        - name: glfw-macos-ninja-release
          run: |
            ./fibs config glfw-macos-ninja-release
            ./fibs build
    ios:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@main
        - uses: denoland/setup-deno@v2
        - name: sapp-metal-ios-xcode-debug
          run: |
            ./fibs config sapp-metal-ios-xcode-debug
            ./fibs build
        - name: sapp-metal-ios-xcode-release
          run: |
            ./fibs config sapp-metal-ios-xcode-release
            ./fibs build
        - name: sapp-gles-ios-xcode-debug
          run: |
            ./fibs config sapp-gles-ios-xcode-debug
            ./fibs build
        - name: sapp-gles-ios-xcode-release
          run: |
            ./fibs config sapp-gles-ios-xcode-release
            ./fibs build
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: ashutoshvarma/setup-ninja@master
        - uses: denoland/setup-deno@v2
        - name: prepare
          run:  |
            sudo apt-get update
            sudo apt-get install mesa-common-dev libx11-dev libvulkan-dev libasound-dev
            cmake --version
        - name: sapp-gl-linux-ninja-debug
          run: |
            ./fibs config sapp-gl-linux-ninja-debug
            ./fibs build
        - name: sapp-gl-linux-ninja-release
          run: |
            ./fibs config sapp-gl-linux-ninja-release
            ./fibs build
        - name: sapp-gl-egl-linux-ninja-debug
          run: |
            ./fibs config sapp-gl-egl-linux-ninja-debug
            ./fibs build
        - name: sapp-gl-egl-linux-ninja-release
          run: |
            ./fibs config sapp-gl-egl-linux-ninja-release
            ./fibs build
        - name: sapp-gles-egl-linux-ninja-debug
          run: |
            ./fibs config sapp-gles-egl-linux-ninja-debug
            ./fibs build
        - name: sapp-gles-egl-linux-ninja-release
          run: |
            ./fibs config sapp-gles-egl-linux-ninja-release
            ./fibs build
        - name: sapp-vk-linux-ninja-debug
          run: |
            ./fibs config sapp-vk-linux-ninja-debug
            ./fibs build
        - name: sapp-vk-linux-ninja-release
          run: |
            ./fibs config sapp-vk-linux-ninja-release
            ./fibs build
        - name: glfw-linux-ninja-debug
          run: |
            ./fibs config glfw-linux-ninja-debug
            ./fibs build
        - name: glfw-linux-ninja-release
          run: |
            ./fibs config glfw-linux-ninja-release
            ./fibs build
    emscripten:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: ashutoshvarma/setup-ninja@master
        - uses: denoland/setup-deno@v2
        - name: install emsdk
          run: ./fibs emsdk install
        - name: sapp-gles-emsc-ninja-debug
          run: |
            ./fibs config sapp-gles-emsc-ninja-debug
            ./fibs build
        - name: sapp-gles-emsc-ninja-release
          run: |
            ./fibs config sapp-gles-emsc-ninja-release
            ./fibs build
        - name: sapp-wgpu-emsc-ninja-debug
          run: |
            ./fibs config sapp-wgpu-emsc-ninja-debug
            ./fibs build
        - name: sapp-wgpu-emsc-ninja-release
          run: |
            ./fibs config sapp-wgpu-emsc-ninja-release
            ./fibs build
        - name: emsc-ninja-debug
          run: |
            ./fibs config emsc-ninja-debug
            ./fibs build
    android:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: ashutoshvarma/setup-ninja@master
        - uses: denoland/setup-deno@v2
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '17'
        - name: install android sdk/ndk
          run: |
            yes | ./fibs android install
        - name: sapp-gles-android-ninja-debug
          run: |
            ./fibs config sapp-gles-android-ninja-debug
            ./fibs build
        - name: sapp-gles-android-ninja-release
          run: |
            ./fibs config sapp-gles-android-ninja-release
            ./fibs build
